name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - uses: actions/checkout@v4

    # Step 2: Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # Step 3: Grant execute permission for gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Step 4: Lint Check
    # Create a lint baseline to bypass pre-existing issues temporarily
    - name: Run Lint
      run: |
        ./gradlew lintDebug || ./gradlew updateLintBaseline
    # Step 5: Build the project
    - name: Build with Gradle
      run: ./gradlew clean build --stacktrace

    # Step 6: Upload APK as an artifact
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
